### ISSUE TITLE
next@12?

### ISSUE THREAD

**Issue by dphuang2** [RevereCRE/relay-nextjs#34]
Hi,

first of all thank you for open sourcing your hard work to integrate react relay into next.js.

I stumbled upon this library when running into trouble integrating the great concepts and implementation of react-relay with the framework capabilities of next.js.

That being said I am starting a project on version 12 of next.js and was wondering if this library has been tested against it?

If not, are there any plans to do so?

Thanks!

**Comment by rrdelaney** [comment]
We have yet to try it out in production because we haven't been able to upgrade to Next.js 12 yet (some peer deps issues), but I've tried it out on a smaller project and the library seems to work fine. It doesn't work with any of the experimental features though, the Relay library apparently isn't a fan of the edge runtime. I keep getting `ReferenceError: global is not defined`.

**Comment by dphuang2** [comment]
> We have yet to try it out in production because we haven't been able to upgrade to Next.js 12 yet (some peer deps issues), but I've tried it out on a smaller project and the library seems to work fine. It doesn't work with any of the experimental features though, the Relay library apparently isn't a fan of the edge runtime. I keep getting `ReferenceError: global is not defined`.

I also ran into that same error. I also tried relay@12 and it failed with “cannot resolve module ‘fs’” when you import GraphQL from babel-plugin-relay/macro. Assuming this is because next js would try to compile for browser but would rail when resolving relay.config.js

**Comment by dphuang2** [comment]
turns out using `import graphql from "babel-plugin-relay/macro"` causes the "fs" issue I ran into. Using `import { graphql } from "react-relay";` works.
