### ISSUE TITLE
`WiredComponent` should always render a `Suspense` on the client

### ISSUE THREAD

**Issue by matthieu-foucault** [RevereCRE/relay-nextjs#41]
Not sure if I'll have time to make a small example, but I observed the following behaviour:
- When rendering a page for the first time on the client, the `CSN` prop is false (meaning it won't be rendered inside a `Suspense` component). Not sure if its an error from my code or if that's always the case
- Now there are two scenarios after this:
  - If we change the page with some client-side routing, `CSN` is back to `true`, and all is well again.
  - If the query variables changes, and we stay on the same page (i.e. by having an action that changes the query string), then `usePreloadedQuery` will throw a promise at some point, but there is no `Suspense` to catch it, so it causes an error and the page fails to render.

I've only tested this with a development build so far, so maybe it's a different behaviour in production.

**Comment by rrdelaney** [comment]
> If we change the page with some client-side routing, CSN is back to true, and all is well again.

This case is intentional, if we render `<Suspense>` on the client's first render there will be a mismatch between the client-generated HTML and the server-generated HTML (or at least React thinks so, despite there not being any actual change in the output). 

> If the query variables changes, and we stay on the same page (i.e. by having an action that changes the query string), then usePreloadedQuery will throw a promise at some point, but there is no Suspense to catch it, so it causes an error and the page fails to render

This is a really good point and definitely a bug that we should fix!

**Comment by alecrobins** [comment]
> If the query variables changes, and we stay on the same page (i.e. by having an action that changes the query string), then usePreloadedQuery will throw a promise at some point, but there is no Suspense to catch it, so it causes an error and the page fails to render

Running into this issue as well when pushing a shallow route that updates a query param used in the page level query.

Verified this works for me https://github.com/bcgov/cas-cif/commit/5d496889871c3a9289068004110baf1404f9ac4e .

Given I was pushing a shallow route, I didn't expect the top level query to run.

**Comment by rrdelaney** [comment]
Thanks for verifying that fix works, I'll fix this and push out a patch later today.

**Comment by alecrobins** [comment]
Thanks! Also, thanks @rrdelaney for maintaining this library 🙏 . It's helped us move very quickly on our project.

**Comment by matthieu-foucault** [comment]
It's more a workaround than a fix, and suffers from the client/server render mismatch issue you noted (i.e. it triggers a warning to be printed in the console).
Noting that this may not be an issue when React 18 is released, as [`Suspense` will be available on the server](https://github.com/reactwg/react-18/discussions/37)

**Comment by rrdelaney** [comment]
Alright, I was able to fix this in a relatively complicated manner. Just re-rendering on mount with the `<Suspense>` wrapper led to some unnecessarily re-renders which caused some jank in on my site, but rendering with `<Suspense>` _always_ on the client-side ends up with React complaining about a markup mismatch. I ended up rendering the wrapper if one of the following are true:

1. The page is being rendered for the first time and it's the client-side
2. The query variables have changed since the initial render

Going to publish this in a new version soon.

**Comment by rrdelaney** [comment]
Alright, created [`v0.6.0`](https://github.com/RevereCRE/relay-nextjs/releases/tag/v0.6.0) and published on npm 😄 Let me know if it fixes your specific issue!

**Comment by mortyccp** [comment]
I have encountered a situation where the page state is lost when first time navigating with a shallow router push. I suspect that this is cased by the switch of render https://github.com/RevereCRE/relay-nextjs/blob/main/src/wired/component.tsx#L113-L123

The `Component` is replaced with another instance for the first shallow router push, thus the local state of the original `Component` is lost.

**Comment by rrdelaney** [comment]
@mortyccp I would recommend against navigating with a shallow router push, this library isn't designed to work with it. Is there a reason you _must_ use shallow navigation?

**Comment by mortyccp** [comment]
Yes, my use case need to navigate with shallow route push.

**Comment by rrdelaney** [comment]
@mortyccp this library is not designed to be used with shallow navigation. It lets Relay figure out when to fetch data or if it should be re-used from the cache. What is the problem you are trying to solve by using shallow navigation?

**Comment by mortyccp** [comment]
I have usage of having a swiper UI for the mobile view that will update the current URL to `page/view1` or `page/view2` and need to preserve the local state of the page. After finding seem the same instance of the page will be used and the state will be kept with or without the shallow navigation. So there is no need for support of shallow navigation atm. But the variable change detection bug still will affect this use case. Since even though the query variable is not updated, it's still detected as changed and trigger a component tree change and the local state is lost due to the old page instance is being replaced.

**Comment by rrdelaney** [comment]
@mortyccp it seems like a fairly easy workaround would be to place the local state that needs persistence in either context or a Relay client schema extension. Those features are designed with your use-case in mind: preserving local state when the component hierarchy might change.
